// <auto-generated />
using Microservice.Customer.Api.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Microservice.Customer.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20240312110435_customer-add-created")]
    partial class customeraddcreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Customer.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa1dc96f-3be5-41cd-8a1b-207284af3fdd"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5677),
                            Email = "jhopkins@hotmail.com",
                            FirstName = "Jane",
                            Surname = "Hopkins"
                        },
                        new
                        {
                            Id = new Guid("af95fb7e-8d97-4892-8da3-5e6e51c54044"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5731),
                            Email = "jarthur@hotmail.com",
                            FirstName = "Arthur",
                            Surname = "James"
                        },
                        new
                        {
                            Id = new Guid("55b431ff-693e-4664-8f65-cfd8d0b14b1b"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5736),
                            Email = "pmohammed@hotmail.com",
                            FirstName = "Mohammed",
                            Surname = "Patel"
                        },
                        new
                        {
                            Id = new Guid("2385de72-2302-4ced-866a-fa199116ca6e"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5739),
                            Email = "smateal@hotmail.com",
                            FirstName = "Sam",
                            Surname = "Mateal"
                        },
                        new
                        {
                            Id = new Guid("47417642-87d9-4047-ae13-4c721d99ab48"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5741),
                            Email = "tabertson@hotmail.com",
                            FirstName = "Tanya",
                            Surname = "Abertson"
                        },
                        new
                        {
                            Id = new Guid("ff4d5a80-81e3-42e3-8052-92cf5c51e797"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5745),
                            Email = "stansor@hotmail.com",
                            FirstName = "Steven",
                            Surname = "Tansor"
                        },
                        new
                        {
                            Id = new Guid("5ff79dfe-c1fa-4dd9-996f-bc96649d6dfc"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5747),
                            Email = "borton@hotmail.com",
                            FirstName = "Beth",
                            Surname = "Orton"
                        },
                        new
                        {
                            Id = new Guid("ae55b0d1-ba02-41e1-9efa-9b4d4ac15eec"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5750),
                            Email = "tamos@hotmail.com",
                            FirstName = "Tori",
                            Surname = "Amos"
                        },
                        new
                        {
                            Id = new Guid("c95ba8ff-06a1-49d0-bc45-83f89b3ce820"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5752),
                            Email = "jpage@hotmail.com",
                            FirstName = "James",
                            Surname = "Page"
                        },
                        new
                        {
                            Id = new Guid("f07e88ac-53b2-4def-af07-957cbb18523c"),
                            Created = new DateTime(2024, 3, 12, 11, 4, 35, 275, DateTimeKind.Local).AddTicks(5755),
                            Email = "josbourne@hotmail.com",
                            FirstName = "John",
                            Surname = "Osbourne"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
