// <auto-generated />
using System;
using Microservice.Customer.Api.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservice.Customer.Api.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20240727104340_create-table-default-data")]
    partial class createtabledefaultdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Customer.Api.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("MSOS_Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c84d0a3-0c0c-435f-9ae0-4de09247ee15"),
                            Created = new DateTime(2024, 7, 27, 11, 43, 40, 6, DateTimeKind.Local).AddTicks(4536),
                            Email = "intergration-test-user@example.com",
                            FirstName = "Intergration_Test",
                            LastUpdated = new DateTime(2024, 7, 27, 11, 43, 40, 6, DateTimeKind.Local).AddTicks(4581),
                            Surname = "Intergration_Test"
                        },
                        new
                        {
                            Id = new Guid("929eaf82-e4fd-4efe-9cae-ce4d7e32d159"),
                            Created = new DateTime(2024, 7, 27, 11, 43, 40, 6, DateTimeKind.Local).AddTicks(4592),
                            Email = "intergration-test-user2@example.com",
                            FirstName = "Intergration_Test2",
                            LastUpdated = new DateTime(2024, 7, 27, 11, 43, 40, 6, DateTimeKind.Local).AddTicks(4594),
                            Surname = "Intergration_Test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
