// <auto-generated />
using Microservice.Customer.Api.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Microservice.Customer.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Customer.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa1dc96f-3be5-41cd-8a1b-207284af3fdd"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1290),
                            Email = "jhopkins@hotmail.com",
                            FirstName = "Jane",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1335),
                            Surname = "Hopkins"
                        },
                        new
                        {
                            Id = new Guid("af95fb7e-8d97-4892-8da3-5e6e51c54044"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1345),
                            Email = "jarthur@hotmail.com",
                            FirstName = "Arthur",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1346),
                            Surname = "James"
                        },
                        new
                        {
                            Id = new Guid("55b431ff-693e-4664-8f65-cfd8d0b14b1b"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1350),
                            Email = "pmohammed@hotmail.com",
                            FirstName = "Mohammed",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1352),
                            Surname = "Patel"
                        },
                        new
                        {
                            Id = new Guid("2385de72-2302-4ced-866a-fa199116ca6e"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1354),
                            Email = "smateal@hotmail.com",
                            FirstName = "Sam",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1356),
                            Surname = "Mateal"
                        },
                        new
                        {
                            Id = new Guid("47417642-87d9-4047-ae13-4c721d99ab48"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1358),
                            Email = "tabertson@hotmail.com",
                            FirstName = "Tanya",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1359),
                            Surname = "Abertson"
                        },
                        new
                        {
                            Id = new Guid("ff4d5a80-81e3-42e3-8052-92cf5c51e797"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1364),
                            Email = "stansor@hotmail.com",
                            FirstName = "Steven",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1365),
                            Surname = "Tansor"
                        },
                        new
                        {
                            Id = new Guid("5ff79dfe-c1fa-4dd9-996f-bc96649d6dfc"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1368),
                            Email = "borton@hotmail.com",
                            FirstName = "Beth",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1370),
                            Surname = "Orton"
                        },
                        new
                        {
                            Id = new Guid("ae55b0d1-ba02-41e1-9efa-9b4d4ac15eec"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1372),
                            Email = "tamos@hotmail.com",
                            FirstName = "Tori",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1373),
                            Surname = "Amos"
                        },
                        new
                        {
                            Id = new Guid("c95ba8ff-06a1-49d0-bc45-83f89b3ce820"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1376),
                            Email = "jpage@hotmail.com",
                            FirstName = "James",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1377),
                            Surname = "Page"
                        },
                        new
                        {
                            Id = new Guid("f07e88ac-53b2-4def-af07-957cbb18523c"),
                            Created = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1381),
                            Email = "josbourne@hotmail.com",
                            FirstName = "John",
                            LastUpdated = new DateTime(2024, 3, 12, 11, 20, 11, 729, DateTimeKind.Local).AddTicks(1382),
                            Surname = "Osbourne"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
